export default [
  {
    id: 1,
    name: 'Tech requirements',
    fileType: 'pdf',
    status: 'Uploaded',
    createdAt: 'Jan 4, 2024',
    createdBy: 'Olivia Rhye',
    createdByEmail: 'olivia@untitledui.com',
  },
  {
    id: 2,
    name: 'Dashboard screenshot',
    fileType: 'jpg',
    status: 'Connected',
    createdAt: 'Jan 4, 2024',
    createdBy: 'Phoenix Baker',
    createdByEmail: 'phoenix@untitledui.com',
  },
  {
    id: 3,
    name: 'Dashboard prototype recording',
    fileType: 'mp4',
    status: 'Connected',
    createdAt: 'Jan 2, 2024',
    createdBy: 'Lana Steiner',
    createdByEmail: 'lana@untitledui.com',
  },
  {
    id: 4,
    name: 'Dashboard prototype FINAL',
    fileType: 'fig',
    status: 'Connected',
    createdAt: 'Jan 8, 2024',
    createdBy: 'Demi Wilkinson',
    createdByEmail: 'demi@untitledui.com',
  },
  {
    id: 5,
    name: 'UX Design Guidelines',
    fileType: 'docx',
    status: 'Connected',
    createdAt: 'Jan 8, 2024',
    createdBy: 'Candice Wu',
    createdByEmail: 'candice@untitledui.com',
  },
  {
    id: 6,
    name: 'Dashboard interaction',
    fileType: 'aep',
    status: 'Error',
    createdAt: 'Jan 6, 2024',
    createdBy: 'Natali',
    createdByEmail: 'natali@untitledui.com',
  },
  {
    id: 7,
    name: 'Dashboard interaction',
    fileType: 'aep',
    status: 'Connected',
    createdAt: 'Jan 6, 2024',
    createdBy: 'Natali',
    createdByEmail: 'natali@untitledui.com',
  }
];
